apiVersion: v1
kind: Pod
metadata:
  name: linuxbox
  labels:
    environment: production
    label2: test
spec:
  terminationGracePeriodSeconds: 5
  restartPolicy: Always
  containers:
    - name: main
      image: iben/ubuntu-16.04-docker-base:latest
