apiVersion: v1
kind: Pod
metadata:
  name: linuxbox3
  labels:
    environment: test
    zone:linux3
  namespace=testns
spec:
  terminationGracePeriodSeconds: 5
  restartPolicy: Always
  containers:
    - name: main
      image: iben/ubuntu-16.04-docker-base:latest
