apiVersion: v1
kind: Pod
metadata:
  name: linuxbox2
  labels:
    environment: production
    zone:linux2
  namespace=testns
spec:
  terminationGracePeriodSeconds: 5
  restartPolicy: Always
  containers:
    - name: main
      image: iben/ubuntu-16.04-docker-base:latest
